- hosts: hadoop
  user: root
  vars:
    hadoop_user: root
  tasks:
  - name: check presto
    tags: ['never', 'install']
    stat:
      path: /opt/presto-server-0.273
    register: work_dir

  - name: install presto
    tags: ['never', 'install']
    unarchive:
      copy: yes
      src: ../../archives/presto-server-0.273.tar.gz
      dest: /opt/
    when: not work_dir.stat.exists

  - name: make config dir
    tags: ['never', 'config']
    file:
      path: /opt/presto-server-0.273/etc
      state: directory

  - name: config presto
    tags: ['never', 'config']
    template:
      src: ./etc/{{ item }}
      dest: /opt/presto-server-0.273/etc/{{ item }}
    with_items:
    - config.properties
    - jvm.config
    - log.properties
    - node.properties

  - name: sync catalog
    tags: ['never', 'sync']
    synchronize:
      src: ./etc/catalog
      dest: /opt/presto-server-0.273/etc/
      delete: true
      checksum: true

  - name: install cli
    tags: ['never', 'cli']
    copy:
      src: ../../archives/presto-cli-0.273-executable.jar
      dest: /opt/presto-server-0.273/presto-cli
      mode: "u=rx,g=rx,o=rx"

  - name: clear data dir
    tags: ['never', 'clear']
    file:
      path: /data/presto
      state: absent
