version: '3.1'

services:
  minio:
    build:
      context: ./service/minio
      args:
        - MINIO_VERSION=${MINIO_VERSION}
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "${BIND_ADDRESS}${BIND_COLON}${MINIO_HTTP_PORT}:9000"
      - "${BIND_ADDRESS}${BIND_COLON}${MINIO_CONSOLE_PORT}:9001"
    command: server --console-address ':9001' /data
    volumes:
      - ${DATA_DIR}/minio/data:/data
