- hosts: ssh
  user: root
  vars:
    work_dir: /opt/docker-service
  tasks:
  - name: make config dir
    tags: ['never', 'config']
    file:
      path: "{{ work_dir }}"
      state: directory

  - name: copy env file
    tags: ['never', 'config']
    copy:
      src: ../../compose/.env
      dest: "{{ work_dir }}/.env"

  - name: config file
    tags: ['never', 'config']
    template:
      src: ../../compose/{{ item }}
      dest: "{{ work_dir }}/{{ item }}"
    with_items:
    - docker-compose.yml

  - name: sync service
    tags: ['never', 'sync']
    synchronize:
      src: ../../compose/service
      dest: "{{ work_dir }}"
      delete: true
      checksum: true
